version: 2
jobs:
  terraform-plan:
    working_directory: ~/app
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - run:
          name: Terrraform `init -> plan`
          command: |
            terraform init -input=false -upgrade
            terraform plan -input=false
      - persist_to_workspace:
          root: ~/app
          paths:
            - .
          
  terraform-apply:
    working_directory: ~/app
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Terrraform `apply`
          command: |
            terraform apply -input=false -auto-approve
      - persist_to_workspace:
          root: ~/app
          paths:
            - .
          
  terraform-destroy:
    working_directory: ~/app
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Terraform `destroy`
          command: terraform apply -destroy
      - persist_to_workspace:
          root: ~/app
          paths:
            - .
          
workflows:
  version: 2
  terraform:
    jobs:
      - terraform-plan
      - terraform-apply:
          requires:
            - terraform-plan
      - terraform-hold-destroy:
          type: approval
      - terraform-destroy:
          requires:
            - terraform-hold-destroy
