version: 2

jobs:
  
  terraform-apply:
    working_directory: .
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terrraform `init - plan - apply`
          command: |
            terraform init -input=false -upgrade
            terraform plan -input=false
            terraform apply -input=false -auto-approve
            
      - persist_to_workspace:
          root: .
          paths:
            - .
  
#  terraform-plan:
#    docker:
#      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
#    steps:
#      - attach_workspace:
#          at: .
#      - run:
#          name: Terraform `plan`
#          command: terraform plan -out=planoutput -input=false
#  terraform-apply:
#    docker:
#      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
#    steps:
#      - attach_workspace:
#          at: .
#      - run:
#          name: Terraform `apply`
#          command: terraform apply -input=false -auto-approve planoutput
  
  terraform-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform `destroy`
          command: terraform apply -destroy
  
  
  
